from enum import Enum
class Skills(Enum):
    Acrobatics = 0,
    AnimalHandling = 1,
    Arcana = 2,
    Athletics = 3,
    Deception = 4,
    History = 5,
    Insight = 6,
    Intimidation = 7,
    Investigation = 8,
    Medicine = 9,
    Nature = 10,
    Perception = 11,
    Performance = 12,
    Persuasion = 13,
    Religion = 14,
    SleightOfHand = 15,
    Stealth = 16,
    Survival = 17