LIGHT_ARMOR = "Light Armor"
MEDIUM_ARMOR = "Medium Armor"
HEAVY_ARMOR = "Heavy Armor"
ALL_ARMOR = {LIGHT_ARMOR,MEDIUM_ARMOR,HEAVY_ARMOR}

SHIELDS = "Shields"

DWARVEN_ARMOR_TRAINING = {LIGHT_ARMOR, MEDIUM_ARMOR}