BATTLEAXE = "Battleaxe"
HANDAXE = "Handaxe"
LIGHT_HAMMER = "Light Hammer"
WARHAMMER = "Warhammer"
LONGSWORD ="Longsword"
SHORTSWORD="Shortsword"
LONGBOW="Longbow"
SHORTBOW="Shortbow"
RAPIER="Rapier"
HAND_CROSSBOW="Hand Crossbow"

DROW_WEAPON_TRAINING = {RAPIER,SHORTSWORD,HAND_CROSSBOW}
DWARVEN_COMBAT_TRAINING = {BATTLEAXE, HANDAXE,LIGHT_HAMMER,WARHAMMER}
ELF_WEAPON_TRAINING = {LONGSWORD,SHORTSWORD,LONGBOW,SHORTBOW}